/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xray.integration;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.TestReporter;

class AppTest {
    @Test void appHasAGreeting(TestReporter testReporter) {
        testReporter.publishEntry("test_key", "XSP-42");
        App classUnderTest = new App();
        System.out.println("!!!!!!TEST!!!!!");
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
