/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xray.integration;

import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.CustomAttribute;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

class AppTest {

    //Arrange
    @DataProvider(name = "loginData")
    public Object[][] getData() {
        return new Object[][] {
                {"60 Days"},
                {"1 Year"}
        };
    }

    @Test(dataProvider = "loginData", groups = "smoke")
    void appHasAGreeting(String username) {
        //Arrange
        Reporter.getCurrentTestResult().setAttribute("test", "XSP-42");

        //Act
        //TODO

        //Assert
        Assert.assertEquals(username,"60 Days");
    }
}
