/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xray.integration;

import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.CustomAttribute;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

class AppTest {

    @DataProvider(name = "loginData")
    public Object[][] getData() {
        return new Object[][] {
                {"user1", "pass1"},
                {"user2", "pass2"}
        };
    }

    @Test(dataProvider = "loginData", groups = "smoke")
    void appHasAGreeting(String username, String password) {
        System.out.println("!!!!!!TEST!!!!!" + username);
        Reporter.getCurrentTestResult().setAttribute("test", "XSP-42");

        Assert.assertEquals(username,"user1");
    }
}
